M48
; DRILL file {KiCad (6.0.1)} date Mon Feb 14 15:35:13 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-14T15:35:13+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X4.9631Y-3.2442
X5.1907Y-3.2442
T2
X4.6832Y-2.263
T3
X5.4706Y-2.263
T0
M30
