M48
; DRILL file {KiCad (6.0.1)} date Fri Feb 11 20:26:02 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-11T20:26:02+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X5.0377Y-2.1625
X5.1047Y-2.1625
X5.5297Y-2.1625
X5.5967Y-2.1625
T0
M30
